#=========================================================
#      ____
#     ╱   ╱╲    Plywood C++ Base Library
#    ╱___╱╭╮╲   https://plywood.dev/
#     └──┴┴┴┘
#=========================================================

set_property(GLOBAL PROPERTY USE_FOLDERS ON)

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "" FORCE)
endif()

set(CMAKE_C_FLAGS "")
set(CMAKE_CXX_FLAGS "")
set(CMAKE_STATIC_LINKER_FLAGS "")
set(CMAKE_SHARED_LINKER_FLAGS "")
set(CMAKE_EXE_LINKER_FLAGS "")

foreach(config_name ${CMAKE_CONFIGURATION_TYPES})
    string(TOUPPER ${config_name} suffix)
    set(CMAKE_C_FLAGS_${suffix} "")
    set(CMAKE_CXX_FLAGS_${suffix} "")
    set(CMAKE_STATIC_LINKER_FLAGS_${suffix} "")
    set(CMAKE_SHARED_LINKER_FLAGS_${suffix} "")
    set(CMAKE_EXE_LINKER_FLAGS_${suffix} "")
endforeach()

if(MSVC)
    set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/DEBUG /INCREMENTAL /EDITANDCONTINUE /LTCG:OFF /SAFESEH:NO")
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/DEBUG /INCREMENTAL:NO")
    set(CMAKE_EXE_LINKER_FLAGS_FINAL "/DEBUG /INCREMENTAL:NO")
    set(CMAKE_C_FLAGS_DEBUG "/D_DEBUG /DPLY_WITH_ASSERTS=1 /MTd /ZI /Od /Ob0 /RTC1")
    set(CMAKE_C_FLAGS_RELEASE "/DNDEBUG /DPLY_WITH_ASSERTS=1 /MT /Zi /O2 /Ob1 /Oi")
    set(CMAKE_C_FLAGS_FINAL "/DNDEBUG /MT /Zi /O2 /Ob1 /Oi")
else()
    set(CMAKE_C_FLAGS "-g -Wall -fno-stack-protector -pthread")
    set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -Wno-invalid-offsetof --std=c++14")
    set(CMAKE_C_FLAGS_DEBUG "-DPLY_WITH_ASSERTS=1 -D_DEBUG")
    set(CMAKE_C_FLAGS_RELEASE "-DPLY_WITH_ASSERTS=1 -Os")
    set(CMAKE_C_FLAGS_FINAL "-Os")
endif()
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
set(CMAKE_CXX_FLAGS_FINAL "${CMAKE_C_FLAGS_FINAL}")

if(IOS)
    include("${CMAKE_CURRENT_LIST_DIR}/../Apple_Developer_ID.cmake") # Should contain: set(CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM <10-character-id>)
elseif(APPLE)
    set(CMAKE_OSX_DEPLOYMENT_TARGET "14.6")
endif()

function(add_source_files var_name root_path)
    set(root_ide_folder "")
    set(directive "")
    set(glob_type GLOB)
    foreach(arg ${ARGN})
        if(directive STREQUAL "IDE_FOLDER")
            set(root_ide_folder "${arg}")
            set(directive "")
        elseif(arg STREQUAL "IDE_FOLDER")
            set(directive "${arg}")
        elseif(arg STREQUAL "RECURSIVE")
            set(glob_type GLOB_RECURSE)
        else()
            list(APPEND glob_patterns "${arg}")
        endif()
    endforeach()
    if(directive STREQUAL "IDE_FOLDER")
        message(FATAL_ERROR "Expected argument after \"${directive}\"")
    endif()
    foreach(glob ${glob_patterns})
        file(${glob_type} file_list RELATIVE "${root_path}" "${root_path}/${glob}")
        if(NOT file_list)
            message(WARNING "No files matching \"${root_path}/${glob}\"")
        endif()
        foreach(rel_file ${file_list})
            # Exclude files that start with .
            if(NOT rel_file MATCHES "^\\..*")
                list(APPEND ${var_name} "${root_path}/${rel_file}")
                get_filename_component(folder "${rel_file}" PATH)
                string(REPLACE / \\ ide_folder "${root_ide_folder}/${folder}")
                source_group("${ide_folder}" FILES "${root_path}/${rel_file}")
            endif()
        endforeach()
    endforeach()
    set(${var_name} "${${var_name}}" PARENT_SCOPE)
endfunction()
